name: UBI IB Collector (Branch)
run-name: ${{ github.actor }} is Collecting a Branch! 🚀
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  Date:
    uses: ./.github/workflows/reusable-date.yml
    permissions: {}

  Skopeo:
    needs: [Date]
    uses: ./.github/workflows/reusable-skopeo.yml
    with:
      date: ${{ needs.Date.outputs.date }}
    secrets: inherit
    permissions:
      contents: read

  Code:
    needs: [Date]
    uses: ./.github/workflows/reusable-code.yml
    with:
      date: ${{ needs.Date.outputs.date }}
      update_submodules: true
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write

  MakeISO:
    needs: [Date, Code, Skopeo]
    uses: ./.github/workflows/reusable-make-iso.yml
    with:
      date: ${{ needs.Date.outputs.date }}
    secrets: inherit
    permissions:
      contents: write
      pull-requests: read

  Release:
    runs-on: ubuntu-24.04
    needs: [Date, MakeISO]
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Show Artifacts
        run: ls -1sh ${{ vars.COLLECTOR }}-*.*

      # Create Release

  Sharepoint:
    runs-on: ubuntu-24.04
    needs: [Date, MakeISO]
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Validate Artifacts
        run: |
          echo -e "Artifacts Downloaded\n$(find . -type f -iname *sha -execdir sha256sum -c {} \;)"

      - name: Show Artifacts
        run: ls -1sh ${{ vars.COLLECTOR }}-*.*

      # Upload files to Sharepoint
