name: UBI-IB ISO Creation
on:
  release:
    types: [edited, released]
  workflow_dispatch:

jobs:
  Date:
    uses: ./.github/workflows/reusable-date.yml
    permissions: {}

  MakeISO:
    needs: [Date]
    uses: ./.github/workflows/reusable-make-iso.yml
    with:
      date: ${{ needs.Date.outputs.date }}
    secrets: inherit
    permissions:
      contents: write
      pull-requests: read

  Sharepoint:
    needs: [Date, MakeISO]
    uses: ./.github/workflows/reusable-sharepoint-upload.yml
    with:
      date: ${{ needs.Date.outputs.date }}
      file_path: "${{ vars.COLLECTOR }}-${{ needs.Date.outputs.date }}.iso*"
    secrets: inherit
    permissions:
      contents: write
      pull-requests: read