name: Reusable - Get Date

on:
  workflow_call:
    outputs:
      date:
        description: "Current date in YYYYMMDD-HHMM format"
        value: ${{ jobs.date.outputs.date }}

jobs:
  date:
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      date: ${{ steps.date.outputs.date }}
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date '+%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
