name: UBI-IB Main Collection Sharepoint Upload
on:
  release:
    types: [edited, released]
  workflow_dispatch:

jobs:
  Date:
    uses: ./.github/workflows/reusable-date.yml

  Sharepoint:
    needs: [Date]
    uses: ./.github/workflows/reusable-sharepoint-upload.yml
    with:
      date: ${{ needs.Date.outputs.date }}
      file_path: "${{ vars.COLLECTOR }}-*.*"
      upload_path_suffix: "${{ needs.Date.outputs.date }}"
    secrets: inherit
    permissions:
      contents: write
      pull-requests: read